language: node_js
node_js: 8
sudo: false

cache:
  directories:
    - node_modules


install:
  - npm install
  - npm install semantic-release@13.1.1
script:
  - npm run lint
  - npm run test

deploy:
  - provider: script
    skip_cleanup: true
    script: npx semantic-release
